title: EDIT_ME I'm the title of the page
description: > # this means to ignore newlines until "baseurl:"
  EDIT_ME description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: /CPWEBBY/docs/ # the subpath of your site, e.g. /blog  EDIT_ME
url: http://kerianvaraine.github.io/ # the base hostname & protocol for your site, e.g. http://example.com     EDIT_ME
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Charlotte Parallel # add your name EDIT_ME
author-img: black_circle.jpg # add your photo
about-author: EDIT_ME  I am the short description below image. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github:  # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
